### ISSUE TITLE
Add "data tables" scenarios

### ISSUE THREAD

**Issue by jbpros** [cucumber-attic/cucumber-tck#10]
I've started adding data tables to cucumber.js and [here is an attempt](https://github.com/cucumber/cucumber-features/blob/data-tables/data_tables.feature) at writing scenarios for those. 

The arrays expressed in doc strings within the `Then` steps are supposed to be pseudocode. However I guess they can be `eval`'ed easily in several languages (JS, Ruby 1.9, ...).

As usual, I warmly welcome all comments and suggestions. And as usual, I have a hard time making up my mind about the style of this feature. :)

@mattwynne If I remember correctly, you kindly proposed to pair up in order to improve the style of the features. I'd be happy to do that at some point, when and if you have the time.

**Comment by mattwynne** [comment]
I made a little correction as a commit, removing a bit of incidental detail.

I would suggest not having the second (hash) scenario. Some languages have hashes, some have other constructs. I'd have thought that could be driven out in unit tests and documented with API documentation for the language-specific table object.

I think the eval'd array is a pretty good idea.

**Comment by jbpros** [comment]
Thank you Matt, that was quick!

It's been a while I wanted to change that step, I shouldn't have used it here. It's used properly in [core.feature](https://github.com/cucumber/cucumber-features/blob/master/core.feature#L17) and we [blindly reused it several times](https://github.com/cucumber/cucumber-features/blob/master/core.feature#L74) afterwards. Boooh! ;) A little refactoring is needed there too.

Good point regarding hashes. Does it mean that this particular functionality is not mandatory? 

If it is mandatory (i.e. we expect implementations to support such a mechanism), what about describing it in a more declarative fashion?

``` cucumber
# "hash" means anything observing the concept of associative arrays, as described 
# on http://en.wikipedia.org/wiki/Associative_array
Scenario: a table interpreted as an array of hashes
  Given a scenario with:
    """
    Given the following cukes:
      | Latin           | English      |
      | Cucumis sativus | Cucumber     |
      | Cucumis anguria | Burr Gherkin |
    """
    And the step "the following cukes:" has a passing mapping that receives hashes
    When Cucumber executes the scenario
    Then the scenario passes
    And the first received hash contains a key "Latin" with value "Cucumis Sativus"
    And the first received hash contains a key "English" with value "Cucumber"
    And the second received hash contains a key "Latin" with value "Cucumis anguria"
    And the second received hash contains a key "English" with value "Burr Gherkin"
```

WDYT?

**Comment by mattwynne** [comment]
Okay so my instinct says that if we want to specify that the data table can be converted into a hash / dictionary, then we can do that declaratively, since we already have a more imperative scenario that gives an example of the gherkin you need to create a table.

So for the hash scenario, we could just say:

``` Gherkin
Scenario: A data table can be read as an array of hashes
  Given the following data table in a step:
    | Latin           | English      |
    | Cucumis sativus | Cucumber     |
    | Cucumis anguria | Burr Gherkin |
  When I receive the data table in a step mapping
  Then I should be able to read it as an array of key value pairs:
    """
    [
      { "Latin":"Cucumis sativus", "English":"Cucumber" },
      { "Latin":"Cucumis anguria", "English":"Burr Gherkin" }
    ]
    """
```

I only used JSON here as I can't think of a neater way to describe an array of hashes. If I implemented this, I would probably connect the step defs / mappings directly to the model objects and test them like that.

**Comment by jbpros** [comment]
I like it! I'll start with that.

Thanks again Matt.

**Comment by mattwynne** [comment]
this is a bit like pairing eh?

**Comment by msassak** [comment]
I like that @mattwynne. Makes me wonder why we don't have a key/value type in Gherkin. :-) The only change I'd make is to reword the steps to focus more on the data table:

``` cucumber
Scenario: A data table can be read as an array of hashes
  Given the following data table in a step:
    | Latin           | English      |
    | Cucumis sativus | Cucumber     |
    | Cucumis anguria | Burr Gherkin |
  When the data table is passed to a step mapping
  Then I can convert the data table to this array of key value pairs:
    """
    [
      { "Latin":"Cucumis sativus", "English":"Cucumber" },
      { "Latin":"Cucumis anguria", "English":"Burr Gherkin" }
    ]
    """
```

**Comment by jbpros** [comment]
@mattwynne We just invented asynchronous pairing! What's great with it is you don't need fancy real-time remote stuff (which is always crap, right?). We could even pair by snail mail! No need for computers! How great is this? :)

@msassak Thanks for the improvements, I think they make sense!

**Comment by jbpros** [comment]
Cucumber's `raw()` and `hashes()` equivalents are described in the [feature](https://github.com/cucumber/cucumber-features/blob/master/data_tables.feature). 

What else is expected on implementations's data tables?

Cucumber::Ast::Table is offering many helpers (e.g. `diff!()`, `rows_hash()`, `column_names()`, `rows()`, etc.). Should all they supply these? Or is the decision left to the discretion of implementors?

**Comment by jbpros** [comment]
It appears that row-based diffs are required on all implementations. Some scenarios should be added for this.

Columns diffs are not needed; they were not added to -jvm (because they are "too complex and confusing", said @aslakhellesoy).

**Comment by jbpros** [comment]
Diff support moved to #12.

**Comment by CharString** [comment]
How does one escape a `|` in a value?

Shouldn't the column width of the first row prescribe which `|`'s are data and which are delimiters?

I'd expect something like #17 to work
