### ISSUE TITLE
Move implementation-agnostic mappings from cucumber-js to cucumber-features

### ISSUE THREAD

**Issue by jbpros** [cucumber-attic/cucumber-tck#11]
There is a bunch of mappings in cucumber.js that could easily be reused by other implementations (e.g.: [assert_passing_scenario](https://github.com/cucumber/cucumber-js/blob/master/features/step_definitions/cucumber_js_mappings.rb#L98)). Let's move them to cucumber-features as much as possible.

**Comment by aslakhellesoy** [comment]
Actually, the output depends on the implementation:

https://github.com/cucumber/cucumber-jvm/blob/master/java/src/test/resources/cucumber-features/cucumber_java_mappings.rb#L283-286

(That's JUnit output)

Let's live with the duplication.

**Comment by msassak** [comment]
IMO the interface (`assert_passing_scenario` and what-not) is more important than the implementation. I think we should focus on sharing the interface.

**Comment by jbpros** [comment]
I was too quick on this one. Agreed guys :)
