### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by jbpros** [cucumber-attic/cucumber-tck#13]
"Cucumber features" is quite confusing when you mention it in conversations. Should we try to find a better name?

@aslakhellesoy I think you used the words _development kit_ during a discussion.

Alternatives to that:
- _Development kit_ (short: _devkit_)
- _Implementor kit_
- _Implementation kit_

Other ideas?

**Comment by aslakhellesoy** [comment]
The term I suggested was [TCK](http://en.wikipedia.org/wiki/Technology_Compatibility_Kit) - so cucumber-tck would be a good name I think.

**Comment by jbpros** [comment]
cucumber-tck sounds good.

**Comment by aslakhellesoy** [comment]
I have renamed the project - let's leave this open until names are changed as well (in READMEs here and there). /cc @msassak

**Comment by jbpros** [comment]
The change [was applied](https://github.com/cucumber/cucumber-js/commit/a8838af7cb756c9130797cecfe282870d1c345d2) to Cucumber.js.

**Comment by jbpros** [comment]
Changed on [Relish](https://www.relishapp.com/cucumber/cucumber-tck) too.

**Comment by josephwilk** [comment]
On 19 Nov 2011, at 13:00, Julien Biezemansreply@reply.github.com wrote:

> "Cucumber features" is quite confusing when you mention it in conversations. Should we try to find a better name?
> 
> @aslakhellesoy I think you used the words _development kit_ during a discussion.
> 
> Alternatives to that:
> - _Development kit_ (short: _devkit_)
> - _Implementor kit_
> - _Implementation kit_
> 
> Other ideas?

Cucumbers living documentation
Cucumbers interface
Cucumbers spec
CukeForCuke

That's the best I can do at this early hour in the morning ;)

Joe

**Comment by jbpros** [comment]
@josephwilk Thanks for the input. We went for "_Cucumber Technology Compatibility Kit_" as found in the Java world. I think it suppresses all ambiguity as we don't use any of those overloaded words like "feature", "spec", "documentation", etc. CukeForCuke's cool though.

Oh and _Technology Compatibility Kit_ feels much more enterprisy. Perhaps this will attract people from _more serious_ technologies =D

**Comment by aslakhellesoy** [comment]
We need to update submodules for cucumber-jvm and cucumber-js ASAP as people are unable to clone properly with stale refs

**Comment by jbpros** [comment]
@aslakhellesoy Did you get any feedback about it? If so, on which repo(s)?

-js should be ok already.

**Comment by aslakhellesoy** [comment]
@flashquartermaster DM'ed me and said:

> Hi,
> 
> Is cucumber-features a defunct project? I'm getting a 404.
> 
> cucumber-js and jvm still link to it and I was planning on using it for Cuke4as3.
> 
> If it has gone is something else going to replace it?
> 
> Best regards
> 
> Tom

**Comment by jbpros** [comment]
Shouldn't we put something on cucumber/cucumber-features with an explanation and link to -tck?

**Comment by aslakhellesoy** [comment]
The project has been renamed, so there is no more cucumber/cucumber-features.

**Comment by msassak** [comment]
I've renamed my repos.

**Comment by mattwynne** [comment]
Nice work! Can we pronounce it 'tick'?

**Comment by jbpros** [comment]
@mattwynne Tick, I like it. :D
