### ISSUE TITLE
Publish these on Relishapp.com

### ISSUE THREAD

**Issue by mattwynne** [cucumber-attic/cucumber-tck#4]
I'll make everyone on the team collaborators on the relish project so we can all push updates.

Until the day someone adds a github push hook for Relish :)

**Comment by jbpros** [comment]
Awesome! Thank you Matt.

**Comment by jbpros** [comment]
Hey Matt,

I tried pushing the features but it seems I don't have the permissions to do it. Could you add me to the project please?

Thank you!

**Comment by mattwynne** [comment]
Hey,

I've added you. The reason I haven't done this yet myself is I got stuck on a yack-shave:

Relish is built to expect to push from a ./features directory, and because this project doesn't have one, you can't push it to Relish. I need to make some changes to the Relish server code to fix that, but they're in the queue behind something else I need to do first!

So this one stalled.

The easy workaround would just be to create a features folder somewhere and clone this repo into it. Then push to relish from the parent directory. Want to give it a try?

**Comment by jbpros** [comment]
I'm going to try the workaround then. Thanks!

**Comment by jbpros** [comment]
There we go: http://relishapp.com/cucumber/cucumber-features

The parent repo workaround did the trick. I guess we can live with it for now :)

**Comment by mattwynne** [comment]
On 6 Aug 2011, at 23:18, jbpros wrote:

> There we go: http://relishapp.com/cucumber/cucumber-features
> 
> The parent repo workaround did the trick. I guess we can live with it for now :)

Nice one! Sorry I let this get stuck.
